# SPDX-FileCopyrightText: The vap-collection Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/policies/best-practices/ban-default-namespace
  - ../../components/policies/best-practices/ban-external-ip-services
  - ../../components/policies/best-practices/ban-localhost-services
  - ../../components/policies/best-practices/ban-nodeport-services
  - ../../components/policies/best-practices/ban-pod-automount-sa-token
  - ../../components/policies/best-practices/ban-sa-automount-sa-token
  - ../../components/policies/best-practices/require-requests-limits
  - ../../components/kustomizations/common-labels
