# SPDX-FileCopyrightText: The vap-collection Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/policies/pod-security-standards/restricted/only-allow-net-bind-service-capability
  - ../../components/policies/pod-security-standards/restricted/require-disabled-privilege-escalation
  - ../../components/kustomizations/common-labels
