# SPDX-FileCopyrightText: The vap-collection Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: ban-default-namespace
  labels:
    app.kubernetes.io/name: ban-default-namespace
    app.kubernetes.io/component: best-practices
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:    ["*"]
        apiVersions:  ["*"]
        operations:   ["CREATE"]
        resources:    ["*"]
        scope:        "Namespaced"
  validations:
    - expression: namespaceObject.metadata.name != 'default'
      message: You must not use the default namespace.
      reason: Invalid
  auditAnnotations:
    - key: name
      valueExpression: string(object.metadata.name)
