# SPDX-FileCopyrightText: The vap-collection Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/policies/pod-security-standards/baseline/ban-host-ipc
  - ../../components/policies/pod-security-standards/baseline/ban-host-network
  - ../../components/policies/pod-security-standards/baseline/ban-host-path
  - ../../components/policies/pod-security-standards/baseline/ban-host-pid
  - ../../components/policies/pod-security-standards/baseline/ban-host-process
  - ../../components/policies/pod-security-standards/baseline/ban-or-restrict-host-ports
  - ../../components/policies/pod-security-standards/baseline/ban-privileged-containers
  - ../../components/policies/pod-security-standards/baseline/ban-selinux-role
  - ../../components/policies/pod-security-standards/baseline/ban-selinux-user
  - ../../components/policies/pod-security-standards/baseline/restrict-apparmor-types
  - ../../components/policies/pod-security-standards/baseline/restrict-container-capabilities
  - ../../components/policies/pod-security-standards/baseline/restrict-proc-mount-type
  - ../../components/policies/pod-security-standards/baseline/restrict-seccomp-profile-types
  - ../../components/policies/pod-security-standards/baseline/restrict-selinux-types
  - ../../components/policies/pod-security-standards/baseline/restrict-sysctls
  - ../../components/kustomizations/common-labels
