# SPDX-FileCopyrightText: The vap-collection Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/policies/pod-security-standards/baseline/ban-host-ipc-usage
  - ../../components/policies/pod-security-standards/baseline/ban-host-network-usage
  - ../../components/policies/pod-security-standards/baseline/ban-host-path-usage
  - ../../components/policies/pod-security-standards/baseline/ban-host-pid-usage
  - ../../components/policies/pod-security-standards/baseline/restrict-container-capabilities
  - ../../components/policies/pod-security-standards/baseline/restrict-sysctls
  - ../../components/kustomizations/common-labels
