# SPDX-FileCopyrightText: The vap-collection Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: restrict-sysctls
  labels:
    app.kubernetes.io/name: restrict-sysctls
    app.kubernetes.io/component: pod-security-standards-baseline
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:    [""]
        apiVersions:  ["v1"]
        operations:   ["CREATE", "UPDATE"]
        resources:    ["pods"]
        scope:        "Namespaced"
      - apiGroups:    ["apps"]
        apiVersions:  ["v1"]
        operations:   ["CREATE", "UPDATE"]
        resources:    ["daemonsets", "deployments", "statefulsets"]
        scope:        "Namespaced"
      - apiGroups:    ["batch"]
        apiVersions:  ["v1"]
        operations:   ["CREATE", "UPDATE"]
        resources:    ["cronjobs", "jobs"]
        scope:        "Namespaced"
  variables:
    - expression: "['kernel.shm_rmid_forced', 'net.ipv4.ip_local_port_range', 'net.ipv4.ip_unprivileged_port_start', 'net.ipv4.tcp_syncookies', 'net.ipv4.ping_group_range']"
      name: allowedSysctls
    - expression: object.spec.?template.?spec.?securityContext.?sysctls.orValue([])
      name: controllerSysctls
    - expression: object.spec.?jobTemplate.?spec.?template.?spec.?securityContext.?sysctls.orValue([])
      name: cronJobSysctls
    - expression: object.spec.?securityContext.?sysctls.orValue([])
      name: podSysctls
    - expression: variables.controllerSysctls + variables.cronJobSysctls + variables.podSysctls
      name: allUsedSysctls
  validations:
    - expression:
        variables.allUsedSysctls.all(sysctl,
          sysctl.name in variables.allowedSysctls)
      messageExpression: "'Any sysctls added beyond the allowed list (' + variables.allowedSysctls.join(', ') + ') are disallowed.'"
      reason: Invalid
  auditAnnotations:
    - key: name
      valueExpression: string(object.metadata.name)
